baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Codects'

theme = 'github.com/canstand/compost'

# required
[build]
_merge = 'deep'

# required
[markup]
_merge = 'deep'

# for better seo
[minify]
_merge = 'deep'

[params.homepage]
  showRecent = true

[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = 1

[[menu.main]]
  name = "About"
  pageRef = "/about"
  weight = 10

[[menu.main]]
  name = "Posts"
  pageRef = "posts"
  weight = 20

[[menu.main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/tcedco/"
  weight = 40

[[menu.main]]
  name = "Instagram"
  url = "https://instagram.com/elsayedcodes/"
  weight = 50